name: Publish Docker Image 

on:
  push:
    branches:
      - master
  

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/arm64,linux/amd64

      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push Node 20 Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: keytelematics/docker-node-awscli:20
          labels: node,awscli
          build-args: NODE_IMAGE=20-bookworm

      - name: Build and push Node 18 Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: keytelematics/docker-node-awscli:18
          labels: node,awscli
          build-args: NODE_IMAGE=18-bookworm

      - name: Build and push Node 16 Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: keytelematics/docker-node-awscli:16
          labels: node,awscli
          build-args: NODE_IMAGE=16-bookworm
            

      - name: Build and push Node 14 Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: keytelematics/docker-node-awscli:14
          labels: node,awscli
          build-args: |
            NODE_IMAGE=14-bullseye
            BREAK_PACKAGES=false
            
